name: Generate HTML and PDF

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate_html:
    name: generate-html
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Set Git Identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: index.html
          github-corners: https://github.com/marcossilvestrini/learning-helm
          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🌐</text></svg>
      
      - name: Commit or Stash Changes
        run: |
          if [[ $(git status -s) ]]; then
            git stash
          fi

      - name: Pull and Rebase
        run: |
          git pull --rebase origin main
      
      - name: Apply Changes
        run: |
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Commit das alterações não confirmadas"          
            git push -f origin main
          fi

      - name: Convert HTML to PDF
        uses: markwilson/html2pdf@v1.0
        with:
          htmlPath: 'index.html'
          pdfName: 'learning-helm'

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: learning-helm
          path: ./learning-helm.pdf
