name: Deploy to gh-pages

on:
  workflow_run:
    workflows: ["Generate HTML"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for Generate HTML to complete
        run: echo "Waiting Generate HTML to complete"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create or update gh-pages branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Cria a branch gh-pages no repositório remoto se não existir
          git push origin --delete gh-pages || true
          git checkout --orphan gh-pages
          git reset --hard
          git clean -ffxd
          git commit --allow-empty -m "Initial commit"
          git push -u origin gh-pages

          # Volta para a branch main
          git checkout main  

      - name: Push to gh-pages
        run: |
          git checkout gh-pages
          git reset --hard origin/main
          git push -f origin gh-pages
