name: Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create gh-pages branch if not exists
        run: |
          git config user.name "marcos.silvestrini"
          git config user.email "marcos.silvestrini@gmail.com"
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages || (git checkout --orphan gh-pages && git push -u origin gh-pages)
          git reset --hard
          git clean -ffxd
          git fetch origin main:main
          git rebase main || true
          git commit --allow-empty -m "Initial commit"  # Adicione um commit vazio
          git push -f origin gh-pages
