name: Release Charts
# on:  
#   workflow_run:
#     workflows: ["Deploy to gh-pages"]
#     types:
#       - completed
on:
  push:
    paths:
      - 'charts/app-silvestrini/*'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "marcos.silvestrini"
          git config user.email "marcos.silvestrini@gmail.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ secrets.PAT }}
        if: steps.check-changes.outputs.changes == 'true'
