name: Release Charts

on:
  # push:
  #   branches:
  #     - main
  workflow_run:
    workflows: ["Generate HTML", "Deploy to gh-pages"]
    types:
      - completed

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Generate HTML and Deploy to gh-pages to complete
        run: echo "Waiting Generate HTML and Deploy to gh-pages to complete"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "marcos.silvestrini"
          git config user.email "marcos.silvestrini@gmail.com"

      - name: Install Helm
        uses: azure/setup-helm@v3      
        env:          
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:                    
          CR_TOKEN: ${{ secrets.PAT }}