name: Release Charts
on:
  push:
    paths:
      - 'charts/app-silvestrini/*'
  # workflow_run:
  #   workflows: ["Deploy to gh-pages"]
  #   types:
  #     - completed

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "marcos.silvestrini"
          git config user.email "marcos.silvestrini@gmail.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Check for changes in charts
        id: check-changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^charts/app-silvestrini/'; then
            echo "Changes detected in charts/app-silvestrini/*"
            echo "::set-output name=changes::true"
          else
            echo "No changes in charts/app-silvestrini/*"
            echo "::set-output name=changes::false"
          fi

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ secrets.PAT }}
        if: steps.check-changes.outputs.changes == 'true'
