name: Update index.yaml

# on:
#   workflow_run:
#     workflows: ["Release Charts"]
#     types:
#       - completed
on:
  push:
    paths:
      - 'charts/app-silvestrini/*'

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current chart version
        id: current-chart-version
        run: |
          current_version=$(yq eval '.version' charts/app-silvestrini/Chart.yaml)
          echo "::set-output name=current_chart_version::$current_version"

      - name: Update index.yaml
        run: |
          chart_version="${{ steps.current-chart-version.outputs.current_chart_version }}"
          sed -i "s/CHART_VERSION/$chart_version/g" templates-index.yaml/template-app-silvestrini.index.yaml
          cp templates-index.yaml/template-app-silvestrini.index.yaml index.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add index.yaml
          git commit -m "Update index.yaml with chart version"
          git push origin main
