name: Update README

on:
  workflow_run:
    workflows: ["Deploy to gh-pages", "Update index.yaml"]
    types:
      - completed

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current chart version
        id: current-chart-version
        run: |
          current_version=$(yq eval '.version' charts/app-silvestrini/Chart.yaml)
          echo "::set-output name=current_chart_version::$current_version"

      - name: Update README
        run: |
          chart_version="${{ steps.current-chart-version.outputs.current_chart_version }}"
          sed -i "s/CHART_VERSION/$chart_version/g" templates-readme.md/app-silvestrini.md
          cp templates-readme.md/app-silvestrini.md charts/app-silvestrini/README.md
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add charts/app-silvestrini/README.md templates-readme.md/app-silvestrini.md  # Adicionando os arquivos às mudanças do Git
          git commit -m "Update index.yaml with chart version"
          git push origin main
