name: Update Index
on:
  push:
    paths:
      - 'charts/app-silvestrini/Chart.yaml'
  pull_request:
    paths:
      - 'charts/app-silvestrini/Chart.yaml'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git pull --rebase origin main

      - name: Get current chart version
        id: current-chart-version
        run: |
          current_version=$(yq eval '.version' charts/app-silvestrini/Chart.yaml)
          echo "::set-output name=current_chart_version::$current_version"

      - name: Update index.yaml
        run: |
          chart_version="${{ steps.current-chart-version.outputs.current_chart_version }}"
          echo "Chart version: {{ chart_version }}"
          cp templates-index.yaml/app-silvestrini-index.yaml index.yaml
          sed -i "s/CHART_VERSION/$chart_version/g" index.yaml

          if git diff --quiet; then
            echo "Nenhuma mudança para commitar"
          else
            git add index.yaml
            git commit -m "Update index.yaml with chart version $chart_version"
            git push origin main
          fi
