name: Update index.yaml

on:
  workflow_run:
    workflows: ["Release Charts"]
    types:
      - completed

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current chart version
        id: current-chart-version
        run: |
          current_version=$(yq eval '.version' charts/app-silvestrini/Chart.yaml)
          echo "::set-output name=current_chart_version::$current_version"

      - name: Get previous chart version from index.yaml
        id: previous-chart-version
        run: |
          previous_version=$(yq eval '.entries.app-silvestrini[0].version' index.yaml)
          echo "::set-output name=previous_chart_version::$previous_version"

      - name: Compare chart versions
        id: compare-versions
        run: |
          current_version="${{ steps.current-chart-version.outputs.current_chart_version }}"
          previous_version="${{ steps.previous-chart-version.outputs.previous_chart_version }}"
          if [ "$current_version" != "$previous_version" ]; then
            echo "::set-output name=chart_version_changed::true"
          else
            echo "::set-output name=chart_version_changed::false"
          fi

      - name: Update index.yaml
        if: steps.compare-versions.outputs.chart_version_changed == 'true'
        run: |
          previous_version="${{ steps.previous-chart-version.outputs.previous_chart_version }}"
          chart_version="${{ steps.current-chart-version.outputs.current_chart_version }}"
          sed -i "s/version: $previous_version/version: $chart_version/" index.yaml
          sed -i "s/app-silvestrini-$previous_version/app-silvestrini-$chart_version/" index.yaml
          sed -i "s/app-silvestrini-$chart_version/app-silvestrini-$previous_version/" index.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Update chart version in index.yaml"
          git push origin main
