name: Update README

on:
  workflow_run:
    workflows: ["Deploy to gh-pages", "Update index.yaml"]
    types:
      - completed

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current chart version
        id: current-chart-version
        run: |
          current_version=$(yq eval '.version' charts/app-silvestrini/Chart.yaml)
          echo "::set-output name=current_chart_version::$current_version"

      - name: Update README
        run: |
          chart_version="${{ steps.current-chart-version.outputs.current_chart_version }}"
          cp templates-readme.md/app-silvestrini.md charts/app-silvestrini/README.md
          sed -i "s/CHART_VERSION/$chart_version/g" charts/app-silvestrini/README.md
          
          
          # Verificar se há mudanças
          if git diff --quiet; then
            echo "Nenhuma mudança para commitar"
          else
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add charts/app-silvestrini/README.md
            git commit -m "Update README with chart version $chart_version"
            git push origin main
          fi
