name: Update index.yaml

on:
  workflow_run:
    workflows: ["Deploy to gh-pages", "Release Charts"]
    types:
      - completed

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current chart version
        id: current-chart-version
        run: |
          current_version=$(yq eval '.version' charts/app-silvestrini/Chart.yaml)
          echo "::set-output name=current_chart_version::$current_version"

      - name: Update index.yaml
        run: |
          chart_version="${{ steps.current-chart-version.outputs.current_chart_version }}"
          cp templates-index.yaml/app-silvestrini-index.yaml index.yaml
          sed -i "s/CHART_VERSION/$chart_version/g" index.yaml          
          
          # Verificar se há mudanças
          if git diff --quiet; then
            echo "Nenhuma mudança para commitar"
          else
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add index.yaml
            git commit -m "Update index.yaml with chart version $chart_version"
            git push origin main
          fi
